//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager.Translations.Source {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManager.Translations.Source.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string GlobalAdd {
            get {
                return ResourceManager.GetString("GlobalAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string GlobalBack {
            get {
                return ResourceManager.GetString("GlobalBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GlobalCancel {
            get {
                return ResourceManager.GetString("GlobalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string GlobalClean {
            get {
                return ResourceManager.GetString("GlobalClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string GlobalCreate {
            get {
                return ResourceManager.GetString("GlobalCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string GlobalCreatedAt {
            get {
                return ResourceManager.GetString("GlobalCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create mov..
        /// </summary>
        public static string GlobalCreateMov {
            get {
                return ResourceManager.GetString("GlobalCreateMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string GlobalDate {
            get {
                return ResourceManager.GetString("GlobalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GlobalDelete {
            get {
                return ResourceManager.GetString("GlobalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product stock, if any, it will be moved to the main location..
        /// </summary>
        public static string GlobalDialogDeleteProductLocationBody {
            get {
                return ResourceManager.GetString("GlobalDialogDeleteProductLocationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string GlobalDialogDeleteTitle {
            get {
                return ResourceManager.GetString("GlobalDialogDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GlobalDialogErrorTitle {
            get {
                return ResourceManager.GetString("GlobalDialogErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string GlobalDialogWarningTitle {
            get {
                return ResourceManager.GetString("GlobalDialogWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GlobalEdit {
            get {
                return ResourceManager.GetString("GlobalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.. something went wrong. Try it again!.
        /// </summary>
        public static string GlobalErrorOperationDB {
            get {
                return ResourceManager.GetString("GlobalErrorOperationDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string GlobalExit {
            get {
                return ResourceManager.GetString("GlobalExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string GlobalInventoryTitle {
            get {
                return ResourceManager.GetString("GlobalInventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string GlobalLocation {
            get {
                return ResourceManager.GetString("GlobalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string GlobalLocations {
            get {
                return ResourceManager.GetString("GlobalLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string GlobalMain {
            get {
                return ResourceManager.GetString("GlobalMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main location.
        /// </summary>
        public static string GlobalMainLocation {
            get {
                return ResourceManager.GetString("GlobalMainLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string GlobalMovement {
            get {
                return ResourceManager.GetString("GlobalMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string GlobalMovementEntry {
            get {
                return ResourceManager.GetString("GlobalMovementEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string GlobalMovementExit {
            get {
                return ResourceManager.GetString("GlobalMovementExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        public static string GlobalMovements {
            get {
                return ResourceManager.GetString("GlobalMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GlobalName {
            get {
                return ResourceManager.GetString("GlobalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string GlobalPassword {
            get {
                return ResourceManager.GetString("GlobalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string GlobalPoweredBy {
            get {
                return ResourceManager.GetString("GlobalPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string GlobalProduct {
            get {
                return ResourceManager.GetString("GlobalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string GlobalProducts {
            get {
                return ResourceManager.GetString("GlobalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string GlobalReference {
            get {
                return ResourceManager.GetString("GlobalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string GlobalRequiredField {
            get {
                return ResourceManager.GetString("GlobalRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GlobalSave {
            get {
                return ResourceManager.GetString("GlobalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global stock.
        /// </summary>
        public static string GlobalStock {
            get {
                return ResourceManager.GetString("GlobalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string GlobalSubmit {
            get {
                return ResourceManager.GetString("GlobalSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string GlobalUser {
            get {
                return ResourceManager.GetString("GlobalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string GlobalUsername {
            get {
                return ResourceManager.GetString("GlobalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string GlobalUsers {
            get {
                return ResourceManager.GetString("GlobalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new location.
        /// </summary>
        public static string LocationCreate {
            get {
                return ResourceManager.GetString("LocationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} location(s)? If has products,  all the stock  will be moved to the main location..
        /// </summary>
        public static string LocationDialogDeleteBody {
            get {
                return ResourceManager.GetString("LocationDialogDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        public static string LocationEdit {
            get {
                return ResourceManager.GetString("LocationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete the main location..
        /// </summary>
        public static string LocationErrorMainLocation {
            get {
                return ResourceManager.GetString("LocationErrorMainLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location with this name already exist..
        /// </summary>
        public static string LocationErrorName {
            get {
                return ResourceManager.GetString("LocationErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location info.
        /// </summary>
        public static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLogin {
            get {
                return ResourceManager.GetString("LoginLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LoginLogout {
            get {
                return ResourceManager.GetString("LoginLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new product.
        /// </summary>
        public static string ProductCreateNewProduct {
            get {
                return ResourceManager.GetString("ProductCreateNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} product(s)?.
        /// </summary>
        public static string ProductDialogDeleteBody {
            get {
                return ResourceManager.GetString("ProductDialogDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ProductEdit {
            get {
                return ResourceManager.GetString("ProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with this reference already exist..
        /// </summary>
        public static string ProductErrorReference {
            get {
                return ResourceManager.GetString("ProductErrorReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product info.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to location.
        /// </summary>
        public static string ProductLocationAddToLocation {
            get {
                return ResourceManager.GetString("ProductLocationAddToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible remove products from the main location.
        /// </summary>
        public static string ProductLocationDeleteErrorMainLocation {
            get {
                return ResourceManager.GetString("ProductLocationDeleteErrorMainLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already associated.
        /// </summary>
        public static string ProductLocationErrorAlreadyAssociated {
            get {
                return ResourceManager.GetString("ProductLocationErrorAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Min.Stock.
        /// </summary>
        public static string ProductLocationMinStockEdit {
            get {
                return ResourceManager.GetString("ProductLocationMinStockEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &quot;{0}&quot;..
        /// </summary>
        public static string ProductLocationMinStockInfo {
            get {
                return ResourceManager.GetString("ProductLocationMinStockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ProductLocationTableHeader {
            get {
                return ResourceManager.GetString("ProductLocationTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create stock movement.
        /// </summary>
        public static string StockMovementCreate {
            get {
                return ResourceManager.GetString("StockMovementCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity that you want to move is higher than the quantity available..
        /// </summary>
        public static string StockMovementErrorQty {
            get {
                return ResourceManager.GetString("StockMovementErrorQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string StockMovementFrom {
            get {
                return ResourceManager.GetString("StockMovementFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string StockMovementLocationDeleted {
            get {
                return ResourceManager.GetString("StockMovementLocationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual stock movement.
        /// </summary>
        public static string StockMovementManualMovement {
            get {
                return ResourceManager.GetString("StockMovementManualMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Stock.
        /// </summary>
        public static string StockMovementMinStock {
            get {
                return ResourceManager.GetString("StockMovementMinStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only main location.
        /// </summary>
        public static string StockMovementOnlyMainLocation {
            get {
                return ResourceManager.GetString("StockMovementOnlyMainLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string StockMovementQty {
            get {
                return ResourceManager.GetString("StockMovementQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock movements.
        /// </summary>
        public static string StockMovementsLabel {
            get {
                return ResourceManager.GetString("StockMovementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string StockMovementsStock {
            get {
                return ResourceManager.GetString("StockMovementsStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Acc..
        /// </summary>
        public static string StockMovementStockAcc {
            get {
                return ResourceManager.GetString("StockMovementStockAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string StockMovementTo {
            get {
                return ResourceManager.GetString("StockMovementTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string UserChangePassword {
            get {
                return ResourceManager.GetString("UserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string UserCreateNewUser {
            get {
                return ResourceManager.GetString("UserCreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string UserCurrentPassword {
            get {
                return ResourceManager.GetString("UserCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} user(s)?.
        /// </summary>
        public static string UserDialogDeleteBody {
            get {
                return ResourceManager.GetString("UserDialogDeleteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string UserEditUser {
            get {
                return ResourceManager.GetString("UserEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete yourself..
        /// </summary>
        public static string UserErrorDeleteYourself {
            get {
                return ResourceManager.GetString("UserErrorDeleteYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string UserErrorInvalidPassword {
            get {
                return ResourceManager.GetString("UserErrorInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and password combination..
        /// </summary>
        public static string UserErrorLogin {
            get {
                return ResourceManager.GetString("UserErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exist..
        /// </summary>
        public static string UserErrorUsername {
            get {
                return ResourceManager.GetString("UserErrorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string UserLastLogin {
            get {
                return ResourceManager.GetString("UserLastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string UserNewPassword {
            get {
                return ResourceManager.GetString("UserNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
    }
}
